# Generated by Django 6.0 on 2025-12-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorles',
            new_name='Categories',
        ),
    ]
