# Generated by Django 6.0 on 2025-12-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_categorles_categories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
